package com.sema4genomics.os.dashboard.entity1;
// Generated 4 Aug, 2017 4:19:25 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panel generated by hbm2java
 */
@Entity
@Table(name = "panel", catalog = "osdashboard")
public class Panel implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Run> runs = new HashSet<Run>(0);

	public Panel() {
	}

	public Panel(int id) {
		this.id = id;
	}

	public Panel(int id, String name, Set<Run> runs) {
		this.id = id;
		this.name = name;
		this.runs = runs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panel")
	public Set<Run> getRuns() {
		return this.runs;
	}

	public void setRuns(Set<Run> runs) {
		this.runs = runs;
	}

}
