package com.entity;
// Generated 4 Aug, 2017 4:03:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SampleRunVariants generated by hbm2java
 */
@Entity
@Table(name = "sample_run_variants", catalog = "osdashboard")
public class SampleRunVariants implements java.io.Serializable {

	private int id;
	private SampleRun sampleRun;

	public SampleRunVariants() {
	}

	public SampleRunVariants(int id, SampleRun sampleRun) {
		this.id = id;
		this.sampleRun = sampleRun;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_run_id", nullable = false)
	public SampleRun getSampleRun() {
		return this.sampleRun;
	}

	public void setSampleRun(SampleRun sampleRun) {
		this.sampleRun = sampleRun;
	}

}
