package com.sema4genomics.os.dashboard.entity;
// Generated 1 Sep, 2017 12:41:39 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BenchPatient generated by hbm2java
 */
@Entity
@Table(name = "bench_patient", catalog = "osdashboard")
public class BenchPatient implements java.io.Serializable {

	private int id;
	private Patient patient;
	private Integer benchPatientId;
	private String benchPatientName;
	private String gender;
	private String familyId;
	private Set<BenchAnalysis> benchAnalysises = new HashSet<BenchAnalysis>(0);

	public BenchPatient() {
	}

	public BenchPatient(int id, Patient patient) {
		this.id = id;
		this.patient = patient;
	}

	public BenchPatient(int id, Patient patient, Integer benchPatientId, String benchPatientName, String gender,
			String familyId, Set<BenchAnalysis> benchAnalysises) {
		this.id = id;
		this.patient = patient;
		this.benchPatientId = benchPatientId;
		this.benchPatientName = benchPatientName;
		this.gender = gender;
		this.familyId = familyId;
		this.benchAnalysises = benchAnalysises;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "bench_patient_id")
	public Integer getBenchPatientId() {
		return this.benchPatientId;
	}

	public void setBenchPatientId(Integer benchPatientId) {
		this.benchPatientId = benchPatientId;
	}

	@Column(name = "bench_patient_name", length = 200)
	public String getBenchPatientName() {
		return this.benchPatientName;
	}

	public void setBenchPatientName(String benchPatientName) {
		this.benchPatientName = benchPatientName;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "family_id", length = 45)
	public String getFamilyId() {
		return this.familyId;
	}

	public void setFamilyId(String familyId) {
		this.familyId = familyId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benchPatient")
	public Set<BenchAnalysis> getBenchAnalysises() {
		return this.benchAnalysises;
	}

	public void setBenchAnalysises(Set<BenchAnalysis> benchAnalysises) {
		this.benchAnalysises = benchAnalysises;
	}

}
