package com.sema4genomics.os.dashboard.entity;
// Generated 1 Sep, 2017 12:41:39 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Doctor generated by hbm2java
 */
@Entity
@Table(name = "doctor", catalog = "osdashboard")
public class Doctor implements java.io.Serializable {

	private int id;
	private String sema4DoctorId;
	private String firstName;
	private String lastName;
	private Set<Order> orders = new HashSet<Order>(0);

	public Doctor() {
	}

	public Doctor(int id, String sema4DoctorId, String firstName, String lastName) {
		this.id = id;
		this.sema4DoctorId = sema4DoctorId;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Doctor(int id, String sema4DoctorId, String firstName, String lastName, Set<Order> orders) {
		this.id = id;
		this.sema4DoctorId = sema4DoctorId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "sema4_doctor_id", nullable = false, length = 50)
	public String getSema4DoctorId() {
		return this.sema4DoctorId;
	}

	public void setSema4DoctorId(String sema4DoctorId) {
		this.sema4DoctorId = sema4DoctorId;
	}

	@Column(name = "first_name", nullable = false, length = 1000)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 1000)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doctor")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
