package com.sema4genomics.os.dashboard.entity;
// Generated 1 Sep, 2017 12:41:39 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "osdashboard")
public class Order implements java.io.Serializable {

	private int id;
	private Doctor doctor;
	private Patient patient;
	private Practice practice;
	private Site site;
	private Date created;
	private String clientOrderId;
	private Set<OrderTest> orderTests = new HashSet<OrderTest>(0);
	private Set<Sample> samples = new HashSet<Sample>(0);

	public Order() {
	}

	public Order(int id, Doctor doctor, Patient patient, Practice practice, Site site) {
		this.id = id;
		this.doctor = doctor;
		this.patient = patient;
		this.practice = practice;
		this.site = site;
	}

	public Order(int id, Doctor doctor, Patient patient, Practice practice, Site site, Date created,
			String clientOrderId, Set<OrderTest> orderTests, Set<Sample> samples) {
		this.id = id;
		this.doctor = doctor;
		this.patient = patient;
		this.practice = practice;
		this.site = site;
		this.created = created;
		this.clientOrderId = clientOrderId;
		this.orderTests = orderTests;
		this.samples = samples;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doctor_id", nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patient_id", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "practice_id", nullable = false)
	public Practice getPractice() {
		return this.practice;
	}

	public void setPractice(Practice practice) {
		this.practice = practice;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "client_order_id", length = 100)
	public String getClientOrderId() {
		return this.clientOrderId;
	}

	public void setClientOrderId(String clientOrderId) {
		this.clientOrderId = clientOrderId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<OrderTest> getOrderTests() {
		return this.orderTests;
	}

	public void setOrderTests(Set<OrderTest> orderTests) {
		this.orderTests = orderTests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Sample> getSamples() {
		return this.samples;
	}

	public void setSamples(Set<Sample> samples) {
		this.samples = samples;
	}

}
