package com.sema4genomics.os.dashboard.entity;
// Generated 1 Sep, 2017 12:41:39 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Practice generated by hbm2java
 */
@Entity
@Table(name = "practice", catalog = "osdashboard")
public class Practice implements java.io.Serializable {

	private int id;
	private String sema4PracticeId;
	private String practiceName;
	private String address1;
	private String address2;
	private String telephone;
	private String fax;
	private String accountNumber;
	private Set<Order> orders = new HashSet<Order>(0);

	public Practice() {
	}

	public Practice(int id, String sema4PracticeId, String practiceName, String accountNumber) {
		this.id = id;
		this.sema4PracticeId = sema4PracticeId;
		this.practiceName = practiceName;
		this.accountNumber = accountNumber;
	}

	public Practice(int id, String sema4PracticeId, String practiceName, String address1, String address2,
			String telephone, String fax, String accountNumber, Set<Order> orders) {
		this.id = id;
		this.sema4PracticeId = sema4PracticeId;
		this.practiceName = practiceName;
		this.address1 = address1;
		this.address2 = address2;
		this.telephone = telephone;
		this.fax = fax;
		this.accountNumber = accountNumber;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "sema4_practice_id", nullable = false, length = 50)
	public String getSema4PracticeId() {
		return this.sema4PracticeId;
	}

	public void setSema4PracticeId(String sema4PracticeId) {
		this.sema4PracticeId = sema4PracticeId;
	}

	@Column(name = "practice_name", nullable = false, length = 500)
	public String getPracticeName() {
		return this.practiceName;
	}

	public void setPracticeName(String practiceName) {
		this.practiceName = practiceName;
	}

	@Column(name = "address_1", length = 1000)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "address_2", length = 1000)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "account_number", nullable = false, length = 50)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "practice")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
