package com.v1.entity;
// Generated 22 Aug, 2017 5:45:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Activities generated by hbm2java
 */
@Entity
@Table(name = "activities", catalog = "gong")
public class Activities implements java.io.Serializable {

	private Integer id;
	private String url;
	private String method;
	private String desc;
	private String urlRegex;
	private Set<PermissionsActivities> permissionsActivitieses = new HashSet<PermissionsActivities>(0);

	public Activities() {
	}

	public Activities(String method) {
		this.method = method;
	}

	public Activities(String url, String method, String desc, String urlRegex,
			Set<PermissionsActivities> permissionsActivitieses) {
		this.url = url;
		this.method = method;
		this.desc = desc;
		this.urlRegex = urlRegex;
		this.permissionsActivitieses = permissionsActivitieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "method", nullable = false, length = 6)
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "desc", length = 200)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "url_regex", length = 200)
	public String getUrlRegex() {
		return this.urlRegex;
	}

	public void setUrlRegex(String urlRegex) {
		this.urlRegex = urlRegex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "activities")
	public Set<PermissionsActivities> getPermissionsActivitieses() {
		return this.permissionsActivitieses;
	}

	public void setPermissionsActivitieses(Set<PermissionsActivities> permissionsActivitieses) {
		this.permissionsActivitieses = permissionsActivitieses;
	}

}
