package com.v1.entity;
// Generated 22 Aug, 2017 5:45:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions", catalog = "gong")
public class Permissions implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<PermissionsActivities> permissionsActivitieses = new HashSet<PermissionsActivities>(0);
	private Set<RolePermissions> rolePermissionses = new HashSet<RolePermissions>(0);

	public Permissions() {
	}

	public Permissions(String name, Set<PermissionsActivities> permissionsActivitieses,
			Set<RolePermissions> rolePermissionses) {
		this.name = name;
		this.permissionsActivitieses = permissionsActivitieses;
		this.rolePermissionses = rolePermissionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissions")
	public Set<PermissionsActivities> getPermissionsActivitieses() {
		return this.permissionsActivitieses;
	}

	public void setPermissionsActivitieses(Set<PermissionsActivities> permissionsActivitieses) {
		this.permissionsActivitieses = permissionsActivitieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permissions")
	public Set<RolePermissions> getRolePermissionses() {
		return this.rolePermissionses;
	}

	public void setRolePermissionses(Set<RolePermissions> rolePermissionses) {
		this.rolePermissionses = rolePermissionses;
	}

}
