package com.v1.entity;
// Generated 22 Aug, 2017 5:45:39 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "gong")
public class Role implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private String roleWeight;
	private Set<UserRoleMapping> userRoleMappings = new HashSet<UserRoleMapping>(0);
	private Set<RolePermissions> rolePermissionses = new HashSet<RolePermissions>(0);

	public Role() {
	}

	public Role(String roleName, String roleWeight, Set<UserRoleMapping> userRoleMappings,
			Set<RolePermissions> rolePermissionses) {
		this.roleName = roleName;
		this.roleWeight = roleWeight;
		this.userRoleMappings = userRoleMappings;
		this.rolePermissionses = rolePermissionses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "role_name", length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_weight", length = 45)
	public String getRoleWeight() {
		return this.roleWeight;
	}

	public void setRoleWeight(String roleWeight) {
		this.roleWeight = roleWeight;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<UserRoleMapping> getUserRoleMappings() {
		return this.userRoleMappings;
	}

	public void setUserRoleMappings(Set<UserRoleMapping> userRoleMappings) {
		this.userRoleMappings = userRoleMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<RolePermissions> getRolePermissionses() {
		return this.rolePermissionses;
	}

	public void setRolePermissionses(Set<RolePermissions> rolePermissionses) {
		this.rolePermissionses = rolePermissionses;
	}

}
