package com.first;
// Generated 31 Aug, 2017 6:35:12 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instrument generated by hbm2java
 */
@Entity
@Table(name = "instrument", catalog = "osdashboard")
public class Instrument implements java.io.Serializable {

	private int id;
	private InstrumentType instrumentType;
	private Site site;
	private String name;
	private String idAtSite;
	private Set<RunCombination> runCombinations = new HashSet<RunCombination>(0);
	private Set<RunCombination> runCombinations_1 = new HashSet<RunCombination>(0);

	public Instrument() {
	}

	public Instrument(int id, InstrumentType instrumentType, Site site) {
		this.id = id;
		this.instrumentType = instrumentType;
		this.site = site;
	}

	public Instrument(int id, InstrumentType instrumentType, Site site, String name, String idAtSite,
			Set<RunCombination> runCombinations, Set<RunCombination> runCombinations_1) {
		this.id = id;
		this.instrumentType = instrumentType;
		this.site = site;
		this.name = name;
		this.idAtSite = idAtSite;
		this.runCombinations = runCombinations;
		this.runCombinations_1 = runCombinations_1;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instrument_type_id", nullable = false)
	public InstrumentType getInstrumentType() {
		return this.instrumentType;
	}

	public void setInstrumentType(InstrumentType instrumentType) {
		this.instrumentType = instrumentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id_at_site", length = 100)
	public String getIdAtSite() {
		return this.idAtSite;
	}

	public void setIdAtSite(String idAtSite) {
		this.idAtSite = idAtSite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Set<RunCombination> getRunCombinations() {
		return this.runCombinations;
	}

	public void setRunCombinations(Set<RunCombination> runCombinations) {
		this.runCombinations = runCombinations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Set<RunCombination> getRunCombinations_1() {
		return this.runCombinations_1;
	}

	public void setRunCombinations_1(Set<RunCombination> runCombinations_1) {
		this.runCombinations_1 = runCombinations_1;
	}

}
