package com.sema4genomics.os.dashboard.entity2;
// Generated 23 Aug, 2017 11:44:23 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instrument generated by hbm2java
 */
@Entity
@Table(name = "instrument", catalog = "gong")
public class Instrument implements java.io.Serializable {

	private int id;
	private Chip chip;
	private InstrumentType instrumentType;
	private Panel panel;
	private Site site;
	private String name;
	private Set<RunQcParameter> runQcParameters = new HashSet<RunQcParameter>(0);
	private Set<Run> runs = new HashSet<Run>(0);

	public Instrument() {
	}

	public Instrument(int id, Chip chip, InstrumentType instrumentType, Panel panel, Site site) {
		this.id = id;
		this.chip = chip;
		this.instrumentType = instrumentType;
		this.panel = panel;
		this.site = site;
	}

	public Instrument(int id, Chip chip, InstrumentType instrumentType, Panel panel, Site site, String name,
			Set<RunQcParameter> runQcParameters, Set<Run> runs) {
		this.id = id;
		this.chip = chip;
		this.instrumentType = instrumentType;
		this.panel = panel;
		this.site = site;
		this.name = name;
		this.runQcParameters = runQcParameters;
		this.runs = runs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chip_id", nullable = false)
	public Chip getChip() {
		return this.chip;
	}

	public void setChip(Chip chip) {
		this.chip = chip;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "instrument_type_id", nullable = false)
	public InstrumentType getInstrumentType() {
		return this.instrumentType;
	}

	public void setInstrumentType(InstrumentType instrumentType) {
		this.instrumentType = instrumentType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "panel_id", nullable = false)
	public Panel getPanel() {
		return this.panel;
	}

	public void setPanel(Panel panel) {
		this.panel = panel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "site_id", nullable = false)
	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Set<RunQcParameter> getRunQcParameters() {
		return this.runQcParameters;
	}

	public void setRunQcParameters(Set<RunQcParameter> runQcParameters) {
		this.runQcParameters = runQcParameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Set<Run> getRuns() {
		return this.runs;
	}

	public void setRuns(Set<Run> runs) {
		this.runs = runs;
	}

}
