package com.sema4genomics.os.dashboard.entity2;
// Generated 23 Aug, 2017 11:44:23 AM by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Panel generated by hbm2java
 */
@Entity
@Table(name = "panel", catalog = "gong")
public class Panel implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Instrument> instruments = new HashSet<Instrument>(0);
	private Set<Target> targets = new HashSet<Target>(0);

	public Panel() {
	}

	public Panel(int id) {
		this.id = id;
	}

	public Panel(int id, String name, Set<Instrument> instruments, Set<Target> targets) {
		this.id = id;
		this.name = name;
		this.instruments = instruments;
		this.targets = targets;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panel")
	public Set<Instrument> getInstruments() {
		return this.instruments;
	}

	public void setInstruments(Set<Instrument> instruments) {
		this.instruments = instruments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "panel")
	public Set<Target> getTargets() {
		return this.targets;
	}

	public void setTargets(Set<Target> targets) {
		this.targets = targets;
	}

}
