package com.latest;
// Generated 31 Aug, 2017 7:26:20 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BenchAnalysis generated by hbm2java
 */
@Entity
@Table(name = "bench_analysis", catalog = "osdashboard")
public class BenchAnalysis implements java.io.Serializable {

	private int id;
	private BenchPatient benchPatient;
	private SampleRun sampleRun;
	private User user;
	private String status;
	private String benchUrl;
	private String benchFolder;
	private String classificationTree;
	private String summary;
	private String description;
	private String igvSessionInfo;
	private Date created;
	private Date lastModified;
	private Set<BenchAnalysisLog> benchAnalysisLogs = new HashSet<BenchAnalysisLog>(0);

	public BenchAnalysis() {
	}

	public BenchAnalysis(int id, BenchPatient benchPatient, SampleRun sampleRun, User user) {
		this.id = id;
		this.benchPatient = benchPatient;
		this.sampleRun = sampleRun;
		this.user = user;
	}

	public BenchAnalysis(int id, BenchPatient benchPatient, SampleRun sampleRun, User user, String status,
			String benchUrl, String benchFolder, String classificationTree, String summary, String description,
			String igvSessionInfo, Date created, Date lastModified, Set<BenchAnalysisLog> benchAnalysisLogs) {
		this.id = id;
		this.benchPatient = benchPatient;
		this.sampleRun = sampleRun;
		this.user = user;
		this.status = status;
		this.benchUrl = benchUrl;
		this.benchFolder = benchFolder;
		this.classificationTree = classificationTree;
		this.summary = summary;
		this.description = description;
		this.igvSessionInfo = igvSessionInfo;
		this.created = created;
		this.lastModified = lastModified;
		this.benchAnalysisLogs = benchAnalysisLogs;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bench_patient_id", nullable = false)
	public BenchPatient getBenchPatient() {
		return this.benchPatient;
	}

	public void setBenchPatient(BenchPatient benchPatient) {
		this.benchPatient = benchPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sample_run_id", nullable = false)
	public SampleRun getSampleRun() {
		return this.sampleRun;
	}

	public void setSampleRun(SampleRun sampleRun) {
		this.sampleRun = sampleRun;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modified_by", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "bench_url", length = 200)
	public String getBenchUrl() {
		return this.benchUrl;
	}

	public void setBenchUrl(String benchUrl) {
		this.benchUrl = benchUrl;
	}

	@Column(name = "bench_folder", length = 45)
	public String getBenchFolder() {
		return this.benchFolder;
	}

	public void setBenchFolder(String benchFolder) {
		this.benchFolder = benchFolder;
	}

	@Column(name = "classification_tree", length = 45)
	public String getClassificationTree() {
		return this.classificationTree;
	}

	public void setClassificationTree(String classificationTree) {
		this.classificationTree = classificationTree;
	}

	@Column(name = "summary", length = 65535)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "igv_session_info", length = 45)
	public String getIgvSessionInfo() {
		return this.igvSessionInfo;
	}

	public void setIgvSessionInfo(String igvSessionInfo) {
		this.igvSessionInfo = igvSessionInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "benchAnalysis")
	public Set<BenchAnalysisLog> getBenchAnalysisLogs() {
		return this.benchAnalysisLogs;
	}

	public void setBenchAnalysisLogs(Set<BenchAnalysisLog> benchAnalysisLogs) {
		this.benchAnalysisLogs = benchAnalysisLogs;
	}

}
