package com.latest;
// Generated 31 Aug, 2017 7:26:20 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "osdashboard")
public class Patient implements java.io.Serializable {

	private int id;
	private String firstName;
	private String lastName;
	private String gender;
	private String dateOfBirth;
	private String mrn;
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<BenchPatient> benchPatients = new HashSet<BenchPatient>(0);

	public Patient() {
	}

	public Patient(int id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Patient(int id, String firstName, String lastName, String gender, String dateOfBirth, String mrn,
			Set<Order> orders, Set<BenchPatient> benchPatients) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.dateOfBirth = dateOfBirth;
		this.mrn = mrn;
		this.orders = orders;
		this.benchPatients = benchPatients;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "first_name", nullable = false, length = 1000)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 1000)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "gender", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "date_of_birth", length = 15)
	public String getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(String dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "MRN", length = 1000)
	public String getMrn() {
		return this.mrn;
	}

	public void setMrn(String mrn) {
		this.mrn = mrn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<BenchPatient> getBenchPatients() {
		return this.benchPatients;
	}

	public void setBenchPatients(Set<BenchPatient> benchPatients) {
		this.benchPatients = benchPatients;
	}

}
