package com.latest;
// Generated 31 Aug, 2017 7:26:20 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RunQcParameter generated by hbm2java
 */
@Entity
@Table(name = "run_qc_parameter", catalog = "osdashboard")
public class RunQcParameter implements java.io.Serializable {

	private int id;
	private RunCombination runCombination;
	private String parameterName;
	private String parameterType;
	private Float min;
	private Float max;
	private Float fixed;
	private Set<RunResult> runResults = new HashSet<RunResult>(0);

	public RunQcParameter() {
	}

	public RunQcParameter(int id, RunCombination runCombination) {
		this.id = id;
		this.runCombination = runCombination;
	}

	public RunQcParameter(int id, RunCombination runCombination, String parameterName, String parameterType, Float min,
			Float max, Float fixed, Set<RunResult> runResults) {
		this.id = id;
		this.runCombination = runCombination;
		this.parameterName = parameterName;
		this.parameterType = parameterType;
		this.min = min;
		this.max = max;
		this.fixed = fixed;
		this.runResults = runResults;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "run_combination_id", nullable = false)
	public RunCombination getRunCombination() {
		return this.runCombination;
	}

	public void setRunCombination(RunCombination runCombination) {
		this.runCombination = runCombination;
	}

	@Column(name = "parameter_name", length = 200)
	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	@Column(name = "parameter_type", length = 45)
	public String getParameterType() {
		return this.parameterType;
	}

	public void setParameterType(String parameterType) {
		this.parameterType = parameterType;
	}

	@Column(name = "min", precision = 12, scale = 0)
	public Float getMin() {
		return this.min;
	}

	public void setMin(Float min) {
		this.min = min;
	}

	@Column(name = "max", precision = 12, scale = 0)
	public Float getMax() {
		return this.max;
	}

	public void setMax(Float max) {
		this.max = max;
	}

	@Column(name = "fixed", precision = 12, scale = 0)
	public Float getFixed() {
		return this.fixed;
	}

	public void setFixed(Float fixed) {
		this.fixed = fixed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "runQcParameter")
	public Set<RunResult> getRunResults() {
		return this.runResults;
	}

	public void setRunResults(Set<RunResult> runResults) {
		this.runResults = runResults;
	}

}
