package com.latest;
// Generated 31 Aug, 2017 7:26:20 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sample generated by hbm2java
 */
@Entity
@Table(name = "sample", catalog = "osdashboard")
public class Sample implements java.io.Serializable {

	private int id;
	private Order order;
	private String limsSampleId;
	private String lisSampleId;
	private String tumorType;
	private String tumorCellularity;
	private Integer accessionNo;
	private String folder;
	private Date created;
	private String lotNumber;
	private Boolean isControlSample;
	private Set<SampleRun> sampleRuns = new HashSet<SampleRun>(0);

	public Sample() {
	}

	public Sample(int id, Order order, String limsSampleId) {
		this.id = id;
		this.order = order;
		this.limsSampleId = limsSampleId;
	}

	public Sample(int id, Order order, String limsSampleId, String lisSampleId, String tumorType,
			String tumorCellularity, Integer accessionNo, String folder, Date created, String lotNumber,
			Boolean isControlSample, Set<SampleRun> sampleRuns) {
		this.id = id;
		this.order = order;
		this.limsSampleId = limsSampleId;
		this.lisSampleId = lisSampleId;
		this.tumorType = tumorType;
		this.tumorCellularity = tumorCellularity;
		this.accessionNo = accessionNo;
		this.folder = folder;
		this.created = created;
		this.lotNumber = lotNumber;
		this.isControlSample = isControlSample;
		this.sampleRuns = sampleRuns;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "lims_sample_id", nullable = false, length = 50)
	public String getLimsSampleId() {
		return this.limsSampleId;
	}

	public void setLimsSampleId(String limsSampleId) {
		this.limsSampleId = limsSampleId;
	}

	@Column(name = "lis_sample_id", length = 50)
	public String getLisSampleId() {
		return this.lisSampleId;
	}

	public void setLisSampleId(String lisSampleId) {
		this.lisSampleId = lisSampleId;
	}

	@Column(name = "tumor_type", length = 45)
	public String getTumorType() {
		return this.tumorType;
	}

	public void setTumorType(String tumorType) {
		this.tumorType = tumorType;
	}

	@Column(name = "tumor_cellularity", length = 45)
	public String getTumorCellularity() {
		return this.tumorCellularity;
	}

	public void setTumorCellularity(String tumorCellularity) {
		this.tumorCellularity = tumorCellularity;
	}

	@Column(name = "accession_no")
	public Integer getAccessionNo() {
		return this.accessionNo;
	}

	public void setAccessionNo(Integer accessionNo) {
		this.accessionNo = accessionNo;
	}

	@Column(name = "folder", length = 45)
	public String getFolder() {
		return this.folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "lot_number", length = 50)
	public String getLotNumber() {
		return this.lotNumber;
	}

	public void setLotNumber(String lotNumber) {
		this.lotNumber = lotNumber;
	}

	@Column(name = "is_control_sample")
	public Boolean getIsControlSample() {
		return this.isControlSample;
	}

	public void setIsControlSample(Boolean isControlSample) {
		this.isControlSample = isControlSample;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sample")
	public Set<SampleRun> getSampleRuns() {
		return this.sampleRuns;
	}

	public void setSampleRuns(Set<SampleRun> sampleRuns) {
		this.sampleRuns = sampleRuns;
	}

}
