package com.latest;
// Generated 31 Aug, 2017 7:26:20 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Target generated by hbm2java
 */
@Entity
@Table(name = "target", catalog = "osdashboard")
public class Target implements java.io.Serializable {

	private int id;
	private Gene gene;
	private RunCombination runCombination;
	private String name;
	private String gene_1;
	private String exons;
	private Set<SampleRunResult> sampleRunResults = new HashSet<SampleRunResult>(0);

	public Target() {
	}

	public Target(int id, Gene gene, RunCombination runCombination) {
		this.id = id;
		this.gene = gene;
		this.runCombination = runCombination;
	}

	public Target(int id, Gene gene, RunCombination runCombination, String name, String gene_1, String exons,
			Set<SampleRunResult> sampleRunResults) {
		this.id = id;
		this.gene = gene;
		this.runCombination = runCombination;
		this.name = name;
		this.gene_1 = gene_1;
		this.exons = exons;
		this.sampleRunResults = sampleRunResults;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gene_id", nullable = false)
	public Gene getGene() {
		return this.gene;
	}

	public void setGene(Gene gene) {
		this.gene = gene;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "run_combination_id", nullable = false)
	public RunCombination getRunCombination() {
		return this.runCombination;
	}

	public void setRunCombination(RunCombination runCombination) {
		this.runCombination = runCombination;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gene", length = 100)
	public String getGene_1() {
		return this.gene_1;
	}

	public void setGene_1(String gene_1) {
		this.gene_1 = gene_1;
	}

	@Column(name = "exons", length = 45)
	public String getExons() {
		return this.exons;
	}

	public void setExons(String exons) {
		this.exons = exons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "target")
	public Set<SampleRunResult> getSampleRunResults() {
		return this.sampleRunResults;
	}

	public void setSampleRunResults(Set<SampleRunResult> sampleRunResults) {
		this.sampleRunResults = sampleRunResults;
	}

}
